services:
  app:
    env_file:
      - .env
    image: ${IMAGE_NAME:-ghcr.io/amusfq/ojs}:${IMAGE_TAG:-latest}
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      OJS_BASE_URL: ${OJS_BASE_URL:-http://localhost:8080}
      OJS_INSTALLED: ${OJS_INSTALLED:-Off}
      DB_DRIVER: ${DB_DRIVER:-mysqli}
      DB_HOST: ${DB_HOST:-your-external-db-host}
      DB_USERNAME: ${DB_USERNAME:-ojs}
      DB_PASSWORD: ${DB_PASSWORD:-change-me}
      DB_DATABASE: ${DB_DATABASE:-ojs}
    volumes:
      - ./files:/var/www/html/files
      - ./config-data:/var/www/html/config-data
