{capture assign="pageTitle"}{if $prevPage}{translate key="archive.archivesPageNumber" pageNumber=$prevPage+1}{else}{translate key="archive.archives"}{/if}{/capture}
{capture assign="homeUrl"}{url page="index" router=$smarty.const.ROUTE_PAGE}{/capture}
{capture assign="searchUrl"}{url page="search"}{/capture}
{capture assign="archivesUrl"}{url page="issue" op="archive"}{/capture}
{capture assign="aboutUrl"}{url page="about"}{/capture}
{capture assign="aboutSubmissionsUrl"}{url page="about" op="submissions"}{/capture}
{capture assign="aboutContactUrl"}{url page="about" op="contact"}{/capture}
{capture assign="viewSubmissionsUrl"}{url page="submissions"}{/capture}
{capture assign="loginUrl"}{url page="login"}{/capture}
{capture assign="profileUrl"}{url page="user" op="profile"}{/capture}
{capture assign="dashboardUrl"}{url page="dashboard"}{/capture}
{capture assign="logoutUrl"}{url page="login" op="signOut"}{/capture}
{capture assign="notificationUrl"}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="notification" op="fetchNotification"}{/capture}
{capture assign="notificationMarkNewUrl"}{url router=PKP\core\PKPApplication::ROUTE_COMPONENT component="grid.notifications.NotificationsGridHandler" op="markNew"}{/capture}
{capture assign="notificationMarkReadUrl"}{url router=PKP\core\PKPApplication::ROUTE_COMPONENT component="grid.notifications.NotificationsGridHandler" op="markRead"}{/capture}
{capture assign="notificationDeleteUrl"}{url router=PKP\core\PKPApplication::ROUTE_COMPONENT component="grid.notifications.NotificationsGridHandler" op="deleteNotifications"}{/capture}
{assign var="logoUrl" value="{$baseUrl}/plugins/themes/thalibulpink/logo_small.png"}
{include file="frontend/components/header.tpl" pageTitleTranslated=$pageTitle}

<div id="thalibul-pink-navbar"></div>
<script type="application/json" id="thalibul-pink-navbar-data">
{ldelim}"journalName": {$currentContext->getLocalizedName()|json_encode nofilter}, "logo": {$logoUrl|json_encode nofilter}, "homeUrl": {$homeUrl|json_encode nofilter}, "searchUrl": {$searchUrl|json_encode nofilter}, "archivesUrl": {$archivesUrl|json_encode nofilter}, "aboutUrl": {$aboutUrl|json_encode nofilter}, "aboutSubmissionsUrl": {$aboutSubmissionsUrl|json_encode nofilter}, "aboutContactUrl": {$aboutContactUrl|json_encode nofilter}, "submissionsUrl": {$viewSubmissionsUrl|json_encode nofilter}, "loginUrl": {$loginUrl|json_encode nofilter}, "profileUrl": {$profileUrl|json_encode nofilter}, "dashboardUrl": {$dashboardUrl|json_encode nofilter}, "logoutUrl": {$logoutUrl|json_encode nofilter}, "loggedIn": {if $isUserLoggedIn}true{else}false{/if}, "notificationCount": {$unreadNotificationCount|default:0|intval}, "notificationUrl": {$notificationUrl|json_encode nofilter}, "notificationMarkNewUrl": {$notificationMarkNewUrl|json_encode nofilter}, "notificationMarkReadUrl": {$notificationMarkReadUrl|json_encode nofilter}, "notificationDeleteUrl": {$notificationDeleteUrl|json_encode nofilter}, "csrfToken": {csrf type="json"}, "username": {$loggedInUsername|default:''|json_encode nofilter}{rdelim}
</script>

<main class="min-h-screen bg-[#f8f9ff] text-slate-900">
	<section class="bg-[#f0f4fd] px-4 py-10 lg:px-12 lg:py-14">
		<div class="mx-auto max-w-[1440px]">
			<div class="flex flex-col justify-between gap-6 lg:flex-row lg:items-end">
				<div><div class="flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#9d3953]"><span>Scholarly repository &amp; open archive</span><span class="text-slate-400">•</span><span class="font-mono font-medium text-[#436465]">{$currentContext->getData('onlineIssn')|default:$currentContext->getData('printIssn')|default:''|escape}</span></div><h1 class="mt-3 text-3xl font-medium tracking-tight text-slate-900 lg:text-4xl">Publication Archives &amp; Indexed Volumes</h1><p class="mt-2 max-w-2xl text-[15px] leading-6 text-slate-600">Browse peer-reviewed issues and published research from {$currentContext->getLocalizedName()|escape}, with each edition linked to its complete table of contents.</p></div>
				<div class="flex flex-wrap items-center gap-3 self-start lg:self-auto"><div class="flex min-h-11 items-center gap-2 bg-white px-4 py-2 shadow-sm"><svg class="h-5 w-5 shrink-0 text-[#436465]" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24" aria-hidden="true"><ellipse cx="12" cy="5" rx="7" ry="3"></ellipse><path d="M5 5v7c0 1.7 3.1 3 7 3s7-1.3 7-3V5M5 12v7c0 1.7 3 3 7 3s7-1.3 7-3v-7"></path></svg><div class="flex flex-col"><span class="text-[10px] leading-3 text-slate-500">Archived Items</span><strong class="text-base font-semibold leading-5 text-slate-900">{$total|default:0}</strong></div></div><div class="flex min-h-11 items-center gap-2 bg-white px-4 py-2 shadow-sm"><svg class="h-5 w-5 shrink-0 text-[#9d3953]" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"></path><path d="M8 6h8M8 10h8"></path></svg><div class="flex flex-col"><span class="text-[10px] leading-3 text-slate-500">Current Page</span><strong class="text-base font-semibold leading-5 text-slate-900">{$showingStart|default:0}–{$showingEnd|default:0}</strong></div></div></div>
			</div>
			<form class="mt-8 flex w-full flex-col gap-3 md:flex-row md:items-stretch" action="{$searchUrl}" method="get"><div class="flex min-h-11 min-w-0 flex-1 items-center border border-slate-200 bg-white px-4 shadow-sm"><span class="mr-3 shrink-0 text-lg text-slate-400">⌕</span><label class="sr-only" for="archive-search">Search archive</label><input class="w-full min-w-0 border-0 bg-transparent text-sm text-slate-800 outline-none" id="archive-search" name="query" placeholder="Search archive: title, author, keyword, abstract, or DOI..." type="search"></div><div class="w-full shrink-0 md:w-44"><select class="thalibul-archive-native-select" data-thalibul-react-select="true" id="archive-search-field" name="searchField"><option value="">All fields</option><option value="title">Title</option><option value="author">Author</option><option value="abstract">Abstract</option></select></div><div class="w-full shrink-0 md:w-auto"><button class="inline-flex min-h-11 w-full items-center justify-center gap-2 whitespace-nowrap bg-[#9d3953] px-5 text-xs font-bold uppercase tracking-wider text-white hover:bg-[#81233e]" type="submit">Search archive <span aria-hidden="true">→</span></button></div></form>
		</div>
	</section>

	<div class="mx-auto grid max-w-[1440px] grid-cols-1 items-start gap-6 px-4 py-10 lg:grid-cols-12 lg:px-12">
		<aside class="flex flex-col gap-5 lg:col-span-4">
			<section class="bg-white p-6 shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 pb-4"><div class="flex items-center gap-2"><span class="text-lg text-[#9d3953]">☷</span><h2 class="text-base font-semibold">Archive guide</h2></div><a class="text-[10px] font-bold uppercase tracking-wider text-[#9d3953] no-underline" href="{$archivesUrl}">Reset</a></div><div class="mt-5 space-y-5"><div><h3 class="text-sm font-semibold text-slate-800">Publication range</h3><p class="mt-2 text-sm leading-6 text-slate-500">Explore the published volumes available in this archive. Select an issue to open its full table of contents.</p></div><div class="border-t border-slate-100 pt-5"><h3 class="text-sm font-semibold text-slate-800">Issue availability</h3><div class="mt-3 space-y-2 text-sm text-slate-600"><div class="flex items-center justify-between bg-[#f0f4fd] px-3 py-2"><span>Published issues</span><strong class="font-mono text-[#9d3953]">{$total|default:0}</strong></div><div class="flex items-center justify-between px-3 py-2"><span>Current view</span><strong class="font-mono text-slate-500">{$showingStart|default:0}–{$showingEnd|default:0}</strong></div></div></div></div></section>
			<section class="border-l-4 border-[#436465] bg-white p-6 shadow-sm"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-[#436465]">Preservation</p><h2 class="mt-2 text-lg font-semibold text-slate-900">A durable scholarly record</h2><p class="mt-3 text-sm leading-6 text-slate-500">Issue pages remain available through the journal archive and link directly to the publication record maintained by OJS.</p></section>
			<section class="bg-[#e4e8f2] p-6"><p class="text-[10px] font-bold uppercase tracking-[.16em] text-slate-500">Need a specific paper?</p><h2 class="mt-2 text-lg font-semibold text-slate-900">Search the full journal</h2><p class="mt-3 text-sm leading-6 text-slate-600">Use the archive search above to find articles, authors, keywords, or identifiers.</p><a class="mt-4 inline-flex text-xs font-bold uppercase tracking-wider text-[#9d3953] no-underline" href="{$searchUrl}">Open search →</a></section>
		</aside>

		<section class="flex flex-col gap-5 lg:col-span-8">
			<div class="flex flex-col justify-between gap-4 bg-white p-4 shadow-sm sm:flex-row sm:items-center"><div class="flex min-w-0 items-center gap-2 overflow-x-auto"><span class="shrink-0 text-[10px] font-bold uppercase tracking-wider text-slate-400">Published issues</span><span class="shrink-0 bg-[#9d3953] px-3 py-1.5 text-xs font-semibold text-white">Newest first</span></div><span class="shrink-0 font-mono text-xs text-slate-400">{$showingStart|default:0}–{$showingEnd|default:0} of {$total|default:0}</span></div>
			{if empty($issues)}
				<div class="bg-white p-8 text-sm leading-6 text-slate-600 shadow-sm">{translate key="current.noCurrentIssueDesc"}</div>
			{else}
				<div class="flex flex-col gap-4">{foreach from=$issues item="issue"}{assign var="issueTitle" value=""}{if $issue->getShowTitle()}{assign var="issueTitle" value=$issue->getLocalizedTitle()}{/if}{assign var="issueSeries" value=$issue->getIssueSeries()}{assign var="issueCover" value=$issue->getLocalizedCoverImageUrl()}{capture assign="issueUrl"}{url page="issue" op="view" path=$issue->getBestIssueId()}{/capture}<article class="group bg-white p-5 shadow-sm transition-shadow hover:shadow-md sm:p-6"><div class="flex flex-col gap-5 sm:flex-row"><a class="flex h-40 w-28 shrink-0 items-center justify-center overflow-hidden bg-[#eaeef8] no-underline" href="{$issueUrl}">{if $issueCover}<img class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105" src="{$issueCover|escape}" alt="{$issue->getLocalizedCoverImageAltText()|escape|default:$issueTitle}">{else}<span class="px-3 text-center text-3xl font-semibold text-[#9d3953]">TIJTL</span>{/if}</a><div class="flex min-w-0 flex-1 flex-col"><div class="flex flex-wrap items-center justify-between gap-2"><span class="bg-[#f4dce7] px-2 py-1 font-mono text-[11px] font-semibold text-[#81233e]">{if $issueSeries}{$issueSeries|escape}{else}{$issueTitle|escape}{/if}</span>{if $issue->getDatePublished()}<time class="font-mono text-xs text-slate-400" datetime="{$issue->getDatePublished()|escape}">{$issue->getDatePublished()|date_format:$dateFormatLong}</time>{/if}</div><h3 class="mt-3 text-xl font-medium leading-snug text-slate-900 group-hover:text-[#9d3953]">{if $issueTitle}{$issueTitle|escape}{else}{$issueSeries|escape}{/if}</h3>{if $issueTitle && $issueSeries}<p class="mt-1 text-xs font-semibold uppercase tracking-wider text-slate-400">{$issueSeries|escape}</p>{/if}<div class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{$issue->getLocalizedDescription()|strip_unsafe_html}</div><div class="mt-auto flex flex-wrap items-center justify-between gap-3 pt-5"><span class="text-[10px] font-bold uppercase tracking-wider text-slate-400">OJS publication record</span><a class="inline-flex items-center text-xs font-bold uppercase tracking-wider text-[#9d3953] no-underline" href="{$issueUrl}">View issue <span class="ml-2 transition-transform group-hover:translate-x-1">→</span></a></div></div></div></article>{/foreach}</div>
				{if $prevPage || $nextPage}<nav class="flex items-center justify-between bg-white p-4 shadow-sm" aria-label="Pagination">{if $prevPage}{if $prevPage > 1}{capture assign="prevUrl"}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="issue" op="archive" path=$prevPage}{/capture}{else}{assign var="prevUrl" value=$archivesUrl}{/if}<a class="border border-slate-200 px-4 py-2 text-xs font-bold uppercase tracking-wider text-slate-600 no-underline hover:border-[#9d3953] hover:text-[#9d3953]" href="{$prevUrl}">← Previous</a>{else}<span></span>{/if}{if $nextPage}{capture assign="nextUrl"}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="issue" op="archive" path=$nextPage}{/capture}<a class="bg-[#9d3953] px-4 py-2 text-xs font-bold uppercase tracking-wider text-white no-underline hover:bg-[#81233e]" href="{$nextUrl}">Next →</a>{/if}</nav>{/if}
			{/if}
		</section>
	</div>
</main>

{include file="frontend/components/footer.tpl"}
